spring.application.name=FacturacionM
server.port=8888

# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/facturacionDB?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Feign + Circuit Breaker (activa el fallback)
spring.cloud.openfeign.circuitbreaker.enabled=true
usuario.service.url=http://localhost:9090

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.packages-to-scan=com.Facturacion.FacturacionM.controller
